### ISSUE TITLE
Seems to lag and crash often

### ISSUE THREAD

**Issue by atonyshepherd** [TarheelGrad1998/gallery-card#8]
I've configured this card with 4 cameras. All are linked through the Xeoma integration and otherwise work just fine. 

I've tried accessing this card both through a web browser and the mobile app (and on a few tablets for that matter), and it seems that if the card loads, sometimes it works perfectly. Other times, I'll click the mini image to switch the big one, and it'll change the text, but the camera image doesn't change, then the whole system slows down until I close whatever had the card open (either the browser tab, or the app). 

It would be really nice if there was an option to update the image at an interval rather than streaming all the entities continuously which I suspect is sucking an enormous amount of memory and causing performance issues.

**Comment by TarheelGrad1998** [comment]
It can be very heavy bandwidth and memory usage when using video/cameras, depending on how it's configured.  

You just have the 4 live camera streams configured on the one card?  Are these high definition cams?  

I configure mine one stream + a set of the recordings on a card, and only have that one card on the page.  One camera is far higher definition than the others so I have to set max files to a lower value.  If it's just the camera streams, maybe see if you have a lower definition feed you can use?

Otherwise, I'll see what I can do to cut back the bandwidth.

**Comment by TarheelGrad1998** [comment]
This is hopefully much improved in v3.4.  Please try and let me know how it goes.
